spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always

server:
  address: 0.0.0.0
  port: ${PORT:8080}
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
sentry:
  dsn: https://67a4c0890cba74b8aa6b49f8c066f5b4@o4506952466563072.ingest.us.sentry.io/4506952468004864
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0