spring:
  datasource:
    url: jdbc:h2:mem:project
    username: "admin"
    password: "admin"

  h2:
    console:
      enabled: true
      # Указываем путь, по которому будет открываться консоль
      path: /h2console/
      settings:
        web-allow-others: true